### ISSUE TITLE
Move GA code to head + update tracking code

### ISSUE THREAD

**Issue by fiskhandlarn** [roots/soil#199]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [x] This is a feature request
- [ ] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/roots/soil/issues)
- [x] I've read the [docs](https://roots.io/soil/docs) and followed them (if applicable)

Replace any `X` with your information.

---

**What is the current behavior?**

1. GA tracking code is outputted in `wp_footer`.
2. Current tracking code outputted is in old format.

**What is the expected or desired behavior?**

1. GA tracking code should be outputted in `wp_head` as per [guidelines](https://support.google.com/analytics/answer/1008080?hl=en&ref_topic=7476230#snippet) (or this should at least be configurable by user).
2. Tracking code outputted should be on the new format per [guidelines](https://support.google.com/analytics/answer/1008080?hl=en&ref_topic=7476230#snippet).

---

**Is there a related [Discourse](https://discourse.roots.io/) thread or were any utilized (please link them)?**

Not that I could find.

---

## Feature Request

**Please provide use cases for changing the current behavior:**

Probably any site using Google Analytics really. :)

**Comment by QWp6t** [comment]
https://github.com/roots/soil/wiki/Google-Analytics

**Comment by fiskhandlarn** [comment]
Thanks! I didn't know about the wiki pages. 

FYI: https://roots.io/soil/docs (linked in "I've read the docs and followed them (if applicable)") redirects to https://roots.io/sage/docs/theme-templates/.

**Comment by fiskhandlarn** [comment]
And what about the new tracking code [Google is recommending](https://support.google.com/analytics/answer/1008080?hl=en&ref_topic=7476230#snippet)?

**Comment by fiskhandlarn** [comment]
@QWp6t And what about the new tracking code [Google is recommending](https://support.google.com/analytics/answer/1008080?hl=en&ref_topic=7476230#snippet)?
